[package]
name = "music_theory"
version = "0.1.0"
authors = ["Alec Deason <alec50@tinycountry.com>"]
edition = "2018"

[dependencies]
ordered-float = "1.0.1"

[dev-dependencies]
assert_approx_eq = "1.1.0"
